### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by CaptnDetergent** [Guichaguri/DiscordDJ#70] opened 2016-05-09 14:31 UTC
I can add youtube links to the queue but I don't know the command(if there is any) to get the bot to play it. The command list doesn't show how to start it either(I may just be blind). Any help would be great.

**Comment by Guichaguri** [comment] 2016-05-09 16:11
Duplicate of #62. The bot is considered broken since the official Discord API is out. I'll update it, but it will take time.

**Closed by Guichaguri** 2016-05-09 16:11 UTC
Labels: bug, duplicate

**Comment by CaptnDetergent** [comment] 2016-05-09 16:50
Oh crap thanks for replying. I thought I did something wrong.
