### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CraftYourWay** [Guichaguri/DiscordDJ#77] opened 2016-08-24 13:46 UTC
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle discord-dj@0.0.5~prestart: discord-dj@0.0.5
6 silly lifecycle discord-dj@0.0.5~prestart: no script for prestart, continuing
7 info lifecycle discord-dj@0.0.5~start: discord-dj@0.0.5
8 verbose lifecycle discord-dj@0.0.5~start: unsafe-perm in lifecycle true
9 verbose lifecycle discord-dj@0.0.5~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/servers/discorddj/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle discord-dj@0.0.5~start: CWD: /servers/discorddj
11 silly lifecycle discord-dj@0.0.5~start: Args: [ '-c', 'node ./runtime/DiscordDJ.js' ]
12 silly lifecycle discord-dj@0.0.5~start: Returned: code: 1  signal: null
13 info lifecycle discord-dj@0.0.5~start: Failed to exec start script
14 verbose stack Error: discord-dj@0.0.5 start: `node ./runtime/DiscordDJ.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid discord-dj@0.0.5
16 verbose cwd /servers/discorddj
17 error Linux 4.4.0-31-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.4.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error discord-dj@0.0.5 start: `node ./runtime/DiscordDJ.js`
22 error Exit status 1
23 error Failed at the discord-dj@0.0.5 start script 'node ./runtime/DiscordDJ.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the discord-dj package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./runtime/DiscordDJ.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs discord-dj
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls discord-dj
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Guichaguri** [comment] 2016-08-24 15:53
Duplicate of #62 
Sorry, since Discord updated and the official API was introduced. I'll update it to the new API, but it will take time.

**Closed by Guichaguri** 2016-08-24 15:53 UTC
Labels: bug, duplicate
