### ISSUE TITLE
Config file problem?

### ISSUE THREAD

**Issue by bitrape** [Guichaguri/DiscordDJ#60] opened 2016-03-15 23:02 UTC
Trying to run v0.0.5 on my raspberry pi. Nodejs / npm are installed.
I have installed ffmpeg with a precompiled package (ffmpeg_2.8.3).

Getting the following error:

```
musicbot@raspberrypi:~ $ ./start-bot.sh
/home/musicbot/runtime/DiscordDJ.js:33
    if(!Utils.exists(config['decoder-path'])) {
                           ^

TypeError: Cannot read property 'decoder-path' of null
    at initDecoders (/home/musicbot/runtime/DiscordDJ.js:33:28)
    at Object.<anonymous> (/home/musicbot/runtime/DiscordDJ.js:324:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
Press [Enter] to close...

```

Sounds like some config file is missing. Tried reinstalling several times, with both Github release / tutorial and npm install discord-dj.

Version numbers:
```
musicbot@raspberrypi:~ $ node -v
v4.4.0
musicbot@raspberrypi:~ $ npm -v
2.14.20
```

Any help is appreciated...

Edit: Btw, I can't even make any settings. Happens at first start after installation.

**Comment by kokarn** [comment] 2016-03-16 15:48
Have you run `./setup-bot.sh?` 
That should create a config file for you in the root `config.json`

**Comment by Guichaguri** [comment] 2016-03-16 17:50
Duplicate of #50

**Closed by Guichaguri** 2016-03-16 17:50 UTC
Labels: duplicate
