### ISSUE TITLE
Help, doesnt work

### ISSUE THREAD

**Issue by bobface123** [Guichaguri/DiscordDJ#67] opened 2016-04-13 02:16 UTC
I'm new to bots and I struggled to download ffmpeg, but got it done. I made a new account for a bot and I think it works, but when it says playing music, and I add a song, it is muted?

**Comment by Guichaguri** [comment] 2016-04-13 18:07
It's a bug in the latest version. Duplicate of #62.
Keep in mind that DiscordDJ is work in progress and everything is for testing and not recommended for actual usage. I still have a lot of old code that needs testing and recoding, sorry for the inconvenience.

**Closed by Guichaguri** 2016-04-13 18:07 UTC
Labels: duplicate
